[package]
name = "evosim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11"
bevy_pancam = {git = "https://github.com/johanhelsing/bevy_pancam.git", branch = "bevy-0.11"}
bevy_rapier2d = {git = "https://github.com/midstreeeam/bevy_rapier.git", branch = "new_dependencies"}
rand = "0.8.5"
